version: 1.0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  publish_nuget: true

nuget:
  account_feed: true

deploy:
  provider: NuGet
  api_key:
    secure: pK3CuJ5xUlPfOnwCZPvFoNPdU326+13zw9GHqrLKLldNNHfaMvST7cbgxRaMGHlS
  skip_symbols: false
  artifact: /.*\.nupkg/
