artifacts:
- path: bin\Debug\netstandard2.0\*.dll
  name: Nuget

branches:
  only:
  - master

deploy:
  provider: NuGet
  api_key:
    secure: pK3CuJ5xUlPfOnwCZPvFoNPdU326+13zw9GHqrLKLldNNHfaMvST7cbgxRaMGHlS
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
